name: Tests

on: [push, pull_request]

jobs:

  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
        python: ['3.6', '3.7', '3.8', '3.9', '3.10', '3.11', '3.12', 'pypy-2.7', 'pypy-3.7', 'pypy-3.8', 'pypy-3.9', 'pypy-3.10']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: python -m pip install build .[tests]

      - name: Downgrade importlib-metadata
        run: python -m pip install importlib-metadata==4.13.0
        if: matrix.python == '3.7' || matrix.python == 'pypy-3.7'

      - name: Flake8 linter
        run: python -m flake8

      - name: Unit tests
        run: python -m pytest --cov
        env:
          DEBUG: true

      - name: Build package
        run: python -m build

      - name: Coverage report
        if: matrix.os == 'ubuntu-20.04' && matrix.python == '3.12'
        run: coverage lcov

      - name: Coveralls
        uses: coverallsapp/github-action@master
        if: matrix.os == 'ubuntu-20.04' && matrix.python == '3.12'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov
